version: "3"

services:
  web:
    build: .
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - .:/code
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
